import Logo from './assets/logo.png'
import Fun from './assets/fun.png'
import Work from './assets/work.png'
import Travel from './assets/Travel.png'
import Personal from './assets/personal.png'
import Callender from './assets/callender1.png'
import HW from './assets/handriting.jpg'
import back from './assets/bg.jpg'
import Avatar from './assets/avatar.png'
export { Logo,Avatar, Fun,HW, Work, Travel, Personal, back, Callender }